### ISSUE TITLE
Softmask elements stop drawing on resolution change sometimes

### ISSUE THREAD

**Issue by NibbleByte** [mob-sakai/SoftMaskForUGUI#208]
**Describe the bug**
Sometimes (for example when I just started the sample project), when tweaking the Power value while the game is running, everything in the soft mask stops drawing. Maximizing the game view (i.e. changing the resolution?) fixes it.
![SoftMaskNotDrawing](https://github.com/user-attachments/assets/a5f3c5c6-bb2c-4af3-95d9-a1166889667f)

Similar thing happens on my original project, often when switching between fullscreen and window and clicking/drag the scrollview? - softmask stops drawing. To go fullscreen I use the Fullscreen Editor plugin (included in the project), but I don't think it's related. (in the gif, I switch to fullscreen via hotkey, so the whole image changes suddenly multiple time). Showing the pause menu overlay also fixes the drawing (enabling game objects?)
![SoftMaskNotDrawing2](https://github.com/user-attachments/assets/cfb5a8bb-4673-4437-b9ad-d6af3c6399d3)

I have updated my project to include the stripped down of my original game setup with all the code. Look for "PaperMap.unity" scene for the game version and "PaperMap-Old.unity" for the previous sample project with the "Power" feature. But generally, both scenes experience the issue, most often on resolution change.

Updated project link: https://drive.google.com/file/d/1rsZ8mC24-38FF9fYEvkh7QYmd80dxJ83/view?usp=sharing

Toggle between windowed mode and fullscreen via "Fullscreen" menu at the top, or F10 hotkey (for me it's ALT+F2).
The scrollview has some components that tweak the behaviour, which may be important?
Note that in my projects, I've turned off assembly and scene reloads (if it makes any difference).

**To Reproduce**
1. Open the "PaperMap.unity" scene. Restart the editor.
2. Check if level icons are visible after opening the editor in the scene. Sometimes they're not. If they're not, toggle fullscreen (not in play mode yet).
3. Play the scene. Code replaces the level icon slots with the "real" instances (deactivates the old, instantiates the new prefabs).
4. Press "Unlock" button at the bottom left corner to show all the levels.
5. Try toggling between fullscreen/maximized/windowed mode, scroll by dragging the content area or the scrollbar, click anywhere. Do these things in different sequence.
6. Note that sometimes masked objects disappear and reappear inconsistently.
7. If objects disappear, press ESC to show the paused menu - objects appear again in the background.

**Environment (please complete the following information):**
 - Version 2.4.0
 - Platform: Windows Editor
 - Unity version: 2023.2.9f1

**Comment by mob-sakai** [comment]
Thank you for your reporting!

**Comment by oktayturkdagli** [comment]
I think you are in the same situation as I was in before. I thought this was solved, but the problem still persists in some spots. Especially when you want to do a masking in scroolview, UISoftMask cannot keep up with the scrolling speed. Especially when done in wordcanvas + scrollview, it really exhibits inconsistencies. I didn't have a chance to download and test your project, but I suggest you try the following temporary solutions.

- Try setting transform sensitivity high in the UISoftMask asset in Assets/ProjectSettings.
- Or try using the anti alising feature instead of the soft mask feature from the soft mask component as a temporary solution.

**Comment by mob-sakai** [comment]
![](https://github.com/user-attachments/assets/937829cb-79f5-4132-9744-fc4c2a040cef)

The issue is reproduced on my environment.
The soft mask buffer is not being updated correctly, or the dirty flag is not set.

**Comment by mob-sakai** [comment]
Fortunately, the issue did not reproduce in the build.

**Comment by mob-sakai** [comment]
The fix was released in v2.4.2. :+1:

**Comment by NibbleByte** [comment]
I've tested it and it works. But I found one issue, not sure if it is related: when I start Unity and it opens this scene initially (on first load) it throws this exception:
```
InvalidOperationException: Accessing game object transform hiearchy before loading of scene has completed. This is not allowed.
UnityEngine.GameObject.GetComponentsInternal (System.Type type, System.Boolean useSearchTypeAsArrayReturnType, System.Boolean recursive, System.Boolean includeInactive, System.Boolean reverse, System.Object resultList) (at <6b66e7caaeb045048a0fbc11f111e6fa>:0)
UnityEngine.GameObject.GetComponentsInChildren[T] (System.Boolean includeInactive, System.Collections.Generic.List`1[T] results) (at <6b66e7caaeb045048a0fbc11f111e6fa>:0)
UnityEngine.Component.GetComponentsInChildren[T] (System.Boolean includeInactive, System.Collections.Generic.List`1[T] result) (at <6b66e7caaeb045048a0fbc11f111e6fa>:0)
Coffee.UISoftMask.UISoftMaskProjectSettings.ResetAllSoftMasks () (at ./Library/PackageCache/com.coffee.softmask-for-ugui@2.4.2/Runtime/ProjectSettings/UISoftMaskProjectSettings.cs:143)
Coffee.UISoftMask.UISoftMaskProjectSettings.OnValidate () (at ./Library/PackageCache/com.coffee.softmask-for-ugui@2.4.2/Runtime/ProjectSettings/UISoftMaskProjectSettings.cs:154)
UnityEditor.PlayerSettings:GetPreloadedAssets()
Coffee.UISoftMaskInternal.PreloadedProjectSettings:GetPreloadedSettings(Type) (at ./Library/PackageCache/com.coffee.softmask-for-ugui@2.4.2/Runtime/Internal/ProjectSettings/PreloadedProjectSettings.cs:68)
Coffee.UISoftMaskInternal.PreloadedProjectSettings:GetDefaultSettings(Type) (at ./Library/PackageCache/com.coffee.softmask-for-ugui@2.4.2/Runtime/Internal/ProjectSettings/PreloadedProjectSettings.cs:75)
Coffee.UISoftMaskInternal.PreloadedProjectSettings`1:get_instance() (at ./Library/PackageCache/com.coffee.softmask-for-ugui@2.4.2/Runtime/Internal/ProjectSettings/PreloadedProjectSettings.cs:142)
Coffee.UISoftMask.UISoftMaskProjectSettings:get_softMaskEnabled() (at ./Library/PackageCache/com.coffee.softmask-for-ugui@2.4.2/Runtime/ProjectSettings/UISoftMaskProjectSettings.cs:73)
Coffee.UISoftMask.SoftMask:GetActualMaskingMode() (at ./Library/PackageCache/com.coffee.softmask-for-ugui@2.4.2/Runtime/SoftMask.cs:705)
Coffee.UISoftMask.SoftMask:SoftMaskingEnabled() (at ./Library/PackageCache/com.coffee.softmask-for-ugui@2.4.2/Runtime/SoftMask.cs:695)
Coffee.UISoftMask.SoftMask:UnityEngine.UI.IMaskable.RecalculateMasking() (at ./Library/PackageCache/com.coffee.softmask-for-ugui@2.4.2/Runtime/SoftMask.cs:482)
Coffee.UISoftMask.SoftMask:OnValidate() (at ./Library/PackageCache/com.coffee.softmask-for-ugui@2.4.2/Runtime/SoftMask.cs:472)
UnityEditor.EditorApplication:Internal_RestoreLastOpenedScenes()
```

If I reload the scene, start, stop play mode, I don't get this exception. Only on Unity startup if this is the first scene.

When this happen, if I press play and click on screen, the softmask stops drawing again. Restarting play mode fixes it - clicking doesn't stop softmask drawing.

**Comment by mob-sakai** [comment]
For now, I reverted the fix. (v2.4.3)

**Comment by mob-sakai** [comment]
@NibbleByte 
> I've tested it and it works. But I found one issue, not sure if it is related: when I start Unity and it opens this scene initially (on first load) it throws this exception:

Umm, it is not reproduced on my environment.
- Mac Editor
- Unity 2023.2.20f1
- SoftMaskForUGUI v2.4.2

**Comment by NibbleByte** [comment]
I have migrated to Unity 6.0.27f1 and it still happens, same callstack.
Could be a Windows thing.

**Comment by NibbleByte** [comment]
I happen to have a MacBook Pro with Sonoma installed. I copied the Unity 6.0.27f1 version (including the Library & UserSettings folders) on it, after platform switch and restart it happened - the same exception. PaperMap scene opened.

**Comment by mob-sakai** [comment]
Thank you.
The issue is reproduced on Windows PC.

**Comment by NibbleByte** [comment]
It's fixed. Thanks a lot :)
